apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/ibm-appconnect.openshift-operators: ""
  name: ibm-appconnect
  namespace: openshift-operators
spec:
  channel: v11.3
  installPlanApproval: Automatic
  name: ibm-appconnect
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
