apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaConnector
metadata:
  name: mq-connector
  labels:
    eventstreams.ibm.com/cluster: kafka-connect-cluster
spec:
  class: com.ibm.eventstreams.connect.mqsource.MQSourceConnector
  tasksMax: 1
  config:
    # the Kafka topic to produce to
    topic: MQ.COMMANDS

    # the MQ queue to get messages from
    mq.queue: COMMANDS.COPY

    # connection details for the queue manager
    mq.queue.manager: MYQMGR
    mq.connection.name.list: queuemanager-ibm-mq(1414)
    mq.channel.name: KAFKA.SVRCONN

    # format of the messages to transfer
    mq.message.body.jms: true
    mq.record.builder: com.ibm.eventstreams.connect.mqsource.builders.JsonRecordBuilder
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter

    # whether to send the schema with the messages
    key.converter.schemas.enable: false
    value.converter.schemas.enable: false

    # transform
    transforms: flatten,redact,drop,origin,casts

    transforms.flatten.type: org.apache.kafka.connect.transforms.Flatten$Value
    transforms.flatten.delimiter: "_"
   
    transforms.redact.type: org.apache.kafka.connect.transforms.MaskField$Value
    transforms.redact.fields: creditcard_number
    transforms.redact.replacement: XXXXXXXXXXXXXXXX

    transforms.drop.type: org.apache.kafka.connect.transforms.ReplaceField$Value
    transforms.drop.blacklist: customer_name

    transforms.origin.type: org.apache.kafka.connect.transforms.InsertField$Value
    transforms.origin.static.field: origin
    transforms.origin.static.value: mq-connector

    transforms.casts.type: org.apache.kafka.connect.transforms.Cast$Value
    transforms.casts.spec: order_quantity:int16

